//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



//INSTANT C# NOTE: Formerly VB.NET project-level imports:
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;

namespace WindowsApplication1
{
	namespace Properties
	{

		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(), global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase
		{

			private static MySettings defaultInstance = (MySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings()));

	#region My.Settings Auto-Save Functionality
//INSTANT C# WARNING: This conditional compilation directive cannot be used in C#:
//	#if _MyType == "WindowsForms"
			private static bool addedHandler;

			private static object addedHandlerLockObject = new object();

			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
			{
				if (My.MyApplication.Application.SaveMySettingsOnExit)
				{
					defaultInstance.Save();
				}
			}
//#endif
	#endregion

			public static MySettings Default
			{
				get
				{

//INSTANT C# WARNING: This conditional compilation directive cannot be used in C#:
//	#if _MyType == "WindowsForms"
					   if (! addedHandler)
					   {
							lock(addedHandlerLockObject)
							{
								if (! addedHandler)
								{
									My.MyApplication.Application.Shutdown += new Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler(AutoSaveSettings);
									addedHandler = true;
								}
							}
						}
//#endif
					return defaultInstance;
				}
			}
		}
	}

//INSTANT C# NOTE: This block was only required to support 'My.Settings' in VB. 'Properties.Settings' is used in C#:
//Namespace My
//
//	<Microsoft.VisualBasic.HideModuleNameAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> Friend Module MySettingsProperty
//
//		<Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> Friend ReadOnly Property Settings() As Global.WindowsApplication1.My.MySettings
//			Get
//				return Global.WindowsApplication1.My.MySettings.Default
//			End Get
//		End Property
//	End Module
//End Namespace

} //end of root namespace