//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



#pragma once

//INSTANT C++ NOTE: Formerly VB.NET project-level imports:
using namespace System;
using namespace System::Collections;
using namespace System::Collections::Generic;
using namespace System::Data;
using namespace System::Drawing;
using namespace System::Diagnostics;
using namespace System::Windows::Forms;

namespace WindowsApplication1
{
	namespace Properties
	{

		//This class was auto-generated by the StronglyTypedResourceBuilder
		//class via a tool like ResGen or Visual Studio.
		//To add or remove a member, edit your .ResX file then rerun ResGen
		//with the /str option, or rebuild your VS project.
		///<summary>
		///  A strongly-typed resource class, for looking up localized strings, etc.
		///</summary>
		[System::CodeDom::Compiler::GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), System::Diagnostics::DebuggerNonUserCodeAttribute(), System::Runtime::CompilerServices::CompilerGeneratedAttribute()]
		private ref class Resources sealed abstract
		{

		private:
			static System::Resources::ResourceManager ^resourceMan;

			static System::Globalization::CultureInfo ^resourceCulture;

			///<summary>
			///  Returns the cached ResourceManager instance used by this class.
			///</summary>
		internal:
			[System::ComponentModel::EditorBrowsableAttribute(System::ComponentModel::EditorBrowsableState::Advanced)]
			static property System::Resources::ResourceManager ^ResourceManager
			{
				System::Resources::ResourceManager ^get();
			}

			///<summary>
			///  Overrides the current thread's CurrentUICulture property for all
			///  resource lookups using this strongly typed resource class.
			///</summary>
			[System::ComponentModel::EditorBrowsableAttribute(System::ComponentModel::EditorBrowsableState::Advanced)]
			static property System::Globalization::CultureInfo ^Culture
			{
				System::Globalization::CultureInfo ^get();
				void set(System::Globalization::CultureInfo ^value);
			}

			static property System::Drawing::Bitmap ^etrac_logo
			{
				System::Drawing::Bitmap ^get();
			}
		};
	}

} //end of root namespace